config/routes.rb
Rails.application.routes.draw do
  resources :hashtags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # post '/questions', to: 'questions#create'
  # patch '/questions/:id', to: 'questions#update'
  # delete '/questions/:id', to: 'questions#destroy'

  root to: 'questions#index'

  resources :questions

  resources :users, param: :nickname, except: %i[index]

  resource :session, only: %i[new create destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_and_belongs_to_many :questions

  validates :name,
            format: { with: /#\w+/ },
            length: { maximum: 280 },
            uniqueness: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', required: false

  has_and_belongs_to_many :hashtags

  validates :body,
            length: { maximum: 280 },
            presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :destroy

  has_secure_password

  def to_param
    nickname
  end

  before_validation :downcase_nickname, :downcase_email

  validates :nickname,
            format: { with: /\A[a-z_]+\z/ },
            length: { maximum: 40 },
            uniqueness: true

  validates :email,
            format: { with: /\A[a-zA-Z0-9_.-]+@[a-zA-Z0-9]+\.[a-zA-Z]+\z/ },
            presence: true,
            uniqueness: true

  validates :navbar_color,
            format: { with: /\A#([[:xdigit:]]{3}){1,2}\z/ },
            allow_nil: true

  include Gravtastic
  gravtastic(secure: true, filetype: :png, size: 100, default: 'retro')

  private

  def downcase_nickname
    nickname.downcase!
  end

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'You are not allowed here!'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: %i[ show edit update destroy ]

  def index
    @hashtags = Hashtag.all
  end

  def show
  end

  def new
    @hashtag = Hashtag.new
  end

  def create
  end

  private
    def set_hashtag
      @hashtag = Hashtag.find(params[:id])
    end

    def hashtag_params
      params.fetch(:hashtag, {})
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit]
  before_action :set_question_for_current_user, only: %i[update destroy edit]

  # hashtags
  after_action :hashtag_check, only: %i[create update]

  def create
    question_params = params.require(:question).permit(:body, :user_id)

    @question = Question.new(question_params)
    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user), notice: 'New question created'
    else
      flash.now[:alert] = 'Please enter the question'

      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)

    @question.update(question_params)

    redirect_to user_path(@question.user), notice: 'Question saved'
  end

  def destroy
    @user = @question.user
    @hashtags = @question.body.scan(/#\w+/)
    @hashtags += @question.answer.scan(/#\w+/) if @question.answer.present?

    @question.destroy

    if @hashtags.present?
      @hashtags.each do |hashtag|
        hashtag = Hashtag.find_by(name: hashtag)
        if hashtag.questions.blank?
          hashtag.destroy
        end
      end
    end

    redirect_to user_path(@user), notice: 'Question deleted'
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.order(created_at: :desc).first(10)
    @users = User.order(created_at: :desc).first(10)
    @hashtags = Hashtag.order(created_at: :desc).first(10)
  end

  def new
    @user = User.find_by!(nickname: params[:user_nickname])
    @question = Question.new(user: @user)
  end

  def edit
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end

  # hashtag
  def hashtag_check
    hashtags = @question.body.scan(/#\w+/)
    hashtags += @question.answer.scan(/#\w+/) if @question.answer.present?
    return true if hashtags.blank?

    hashtags.each do |tag|
      tag = tag.downcase
      if Hashtag.where(name: tag).present?
        @new_hashtag = Hashtag.find_by(name: tag)
      else
        @new_hashtag = Hashtag.create(name: tag)
      end
      @new_hashtag.questions += [@question]
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Login successful!'
    else
      flash[:alert] = 'Wrong email or password'

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Registration successful!'
    else
      flash.now[:alert] = 'Please check the information you gave'

      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Details updated'
    else
      flash.now[:alert] = 'Error saving'

      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'User deleted'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @question = Question.new(user: @user)
  end

  private

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.find_by!(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation, :navbar_color
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def inclination(count, one, many)
    if count == 1
      one
    else
      many
    end
  end

end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def find_author(question)
    User.find_by(id: question.author_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    "@#{user.nickname}"
  end
end

app/views/hashtags/_hashtag.html.erb
<div class="mb-sm mt-sm">
  <%= link_to hashtag.name, hashtag_path(hashtag) %>
</div>

app/views/hashtags/show.html.erb
<div class="container">
  <h3 class="text-bold">Questions with "<%= @hashtag.name %>"</h3>
  <% @hashtag.questions.each do |question| %>
    <div class="mt-md">
      <%= render partial: 'questions/question', locals: {question: question} %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <div class="wrapper">
    <div class="navbar" style="background-color: <%= current_user.navbar_color if current_user %>" >
      <p class="title-sm text-bold"><%= link_to 'Ask me!', root_path %></p>
      <div>
        <% if current_user.present? %>
          <%= link_to display_nickname(current_user), user_path(current_user), class: 'mr-sm' %>
          <%= button_to 'Logout', session_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign up', new_user_path, class: 'button button-yellow mr-sm' %>
          <%= link_to 'Login', new_session_path, class: 'button button-yellow' %>
        <% end %>
      </div>
    </div>

    <% if flash[:notice].present? %>
      <p class="mb mt message message-notice"><%= flash[:notice] %></p>
    <% elsif flash.now[:alert].present? %>
      <p class="mb mt message message-alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/questions/_author.html.erb
<div class="text-bold mt-sm">
  <% if author.present? %>
    <p>From:
      <%= link_to display_nickname(author), user_path(author), class: 'mr-sm' %>
    </p>
  <% else %>
    <p class="text-blue">Anonymous</p>
  <% end %>
</div>

app/views/questions/_form.html.erb
<%= form_with model: question, data: {turbo: false} do |form| %>
  <%= form.hidden_field :user_id %>

  <p><%= form.label :body, "Question text" %></p>
  <p><%= form.text_area :body, rows: 5, class: "form-text-area" %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, "Answer" %></p>
    <p><%= form.text_area :answer, rows: 5, class: "form-text-area" %></p>
  <% end %>

  <p class="mt"><%= form.submit "Save", class: "button button-main" %></p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm">
  <%= simple_format strip_tags(sanitize(question.body)) %>
</div>

<% if question.answer.present? %>
  <div class="mb-sm text-dark-red">
    <%= simple_format strip_tags(sanitize(question.answer)) %>
  </div>
<% end %>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>
    <%= render 'questions/author', author: find_author(question) %>
  </div>

  <% if current_user == question.user %>
    <div>
      <% edit_icon = (question.answer.present?) ? 'pencil' : 'reply' %>
      <%= link_to fa_icon(edit_icon), edit_question_path(question),
                  title: "Edit question", class: 'mr-sm' %>
      <%= button_to fa_icon("trash-o"), question_path(question),
                    method: :delete, title: "Delete question",
                    form: {data: {turbo_confirm: "Are you sure you want to delete?"}} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Edit question <%= @question.id %></h2>

  <%= render 'form', question: @question %>

  <p class="mt">
    <%= link_to "Go back", :back %>
  </p>
</div>

app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb">
    Recently registered
  </h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: {user: user} %>
    <% end %>
  </div>
</div>

<% if @hashtags.present? %>
  <div class="container mt-sm">
    <h2 class="text-bold">Hashtags</h2>
    <div class="hashtags-box">
      <% @hashtags.each do |hashtag| %>
        <div class="hashtag"><%= render partial: 'hashtags/hashtag', locals: {hashtag: hashtag} %></div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="container mt-sm">
  <h2 class="title-lg">
    Last
    <%= @questions.count %>
    <%= inclination(@questions.count, 'question', 'questions') %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <p class="mb text-sm text-grey">
      Question <%= link_to "##{question.id}", question_path(question) %>
      for user <%= link_to "@#{question.user.nickname}", user_path(question.user) %>
    </p>
    <%= render question %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">New question</h2>
  <% if @user.present? %>
    <p class="mb">for <%= link_to display_nickname(@user), user_path(@user) %></p>
  <% end %>

  <% if @question.errors.any? %>
    <div class="mt">
      <% @question.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= render 'form', question: @question %>
  </div>

</div>

app/views/questions/show.html.erb
<div class="container">

  <h2 class="title-lg mb">Question <%= @question.id %></h2>
  <p class="mt-sm">
    <%= link_to "All questions for @#{@question.user.nickname}", user_path(@question.user) %>
  </p>

</div>

<div class="container mt-sm">
  <%= render 'question', question: @question %>
</div>

app/views/users/_empty.html.erb
<div class="container mt-sm center-text">
  <h2 class="title-md">This user has no questions yet</h2>
  <p class="text-bold text-grey mt-sm">Why don't you be the first to ask?</p>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user <%= background_class %> rounded mr ml">
  <a href="<%= user_path(user) %>">
    <%= image_tag user.gravatar_url, title: "@#{user.nickname}", class: 'rounded' %>
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Edit user</h2>

  <div class="mt">
    <p><%= image_tag @user.gravatar_url, title: display_nickname(@user), class: 'rounded' %></p>
    <p class="text-sm mt-sm">To edit your profile picture - register on
      <%= link_to 'Gravatar', 'https://gravatar.com' %> and upload a photo!</p>
  </div>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, 'Name' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Nickname' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt-lg text-sm">If you don't want to change your password, leave blank</p>

      <p class="mt"><%= form.label :password, 'Password' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation, 'Password confirmation' %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :navbar_color, 'Navbar color' %></p>
      <p><%= form.color_field :navbar_color %></p>

      <p class="mt-lg">
        <%= form.submit 'Save', class: 'button button-main' %>
        <span class="text-sm">or <%= link_to 'go back', :back %></span>
      </p>

  <% end %>
  </div>

  <div class="mt-lg">
    <%= button_to 'Delete profile', user_path(@user),
      method: :delete,
      form: {data: {turbo_confirm: 'Are you sure you want to delete your profile?'}},
      class: 'text-red text-sm' %>

  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Connect and ask!</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, 'Your name' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Nickname' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg"><%= form.submit 'Create account', class: 'button button-main' %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-box">
  <h2 class="title-lg mt-lg"><%= @user.name %></h2>

  <div class="mt">
    <%= render partial: 'users/user_avatar', locals: {user: @user} %>
  </div>

  <% if current_user == @user %>
    <p class="mt mb-lg">
      <%= link_to fa_icon('pencil'), edit_user_path(@user) %>
    </p>
  <% end %>

  <p class="text-bold mt mb-lg"><%= @user.nickname %></p>
</div>

<div class="container">
  <%= link_to 'Ask me', new_question_path(user_nickname: @user.nickname), class: 'button button-yellow' %>

  <p class="mt">
    <%= render 'questions/form', question: @question %>
  </p>
</div>

<% if @user.questions.empty? %>

  <%= render 'empty' %>

<% else %>

  <div class="container mt-sm">
    <h2 class="title-lg">
      <%= @questions.count %>
      <%= inclination(@questions.count, 'question', 'questions') %>
    </h2>
  </div>

  <% @questions.each do |question| %>
    <div class="mt-sm container">
      <%= render question %>
    </div>
  <% end %>

<% end %>